/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedUnitsIndexRouteImport } from './routes/_authenticated/units/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedUnitsByProjectRouteImport } from './routes/_authenticated/units/by-project'
import { Route as AuthenticatedUnitsAvailabilityRouteImport } from './routes/_authenticated/units/availability'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsProjectsRouteImport } from './routes/_authenticated/settings/projects'
import { Route as AuthenticatedSettingsExportRouteImport } from './routes/_authenticated/settings/export'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated/reports/sales'
import { Route as AuthenticatedReportsRevenueRouteImport } from './routes/_authenticated/reports/revenue'
import { Route as AuthenticatedReportsOccupancyRouteImport } from './routes/_authenticated/reports/occupancy'
import { Route as AuthenticatedReportsCustomRouteImport } from './routes/_authenticated/reports/custom'
import { Route as AuthenticatedReportsCollectionRouteImport } from './routes/_authenticated/reports/collection'
import { Route as AuthenticatedProjectsDashboardRouteImport } from './routes/_authenticated/projects/dashboard'
import { Route as AuthenticatedProjectsCustomerOverviewRouteImport } from './routes/_authenticated/projects/customer-overview'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedCustomersCreateRouteImport } from './routes/_authenticated/customers/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnitsIndexRoute = AuthenticatedUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUnitsByProjectRoute =
  AuthenticatedUnitsByProjectRouteImport.update({
    id: '/units/by-project',
    path: '/units/by-project',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUnitsAvailabilityRoute =
  AuthenticatedUnitsAvailabilityRouteImport.update({
    id: '/units/availability',
    path: '/units/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProjectsRoute =
  AuthenticatedSettingsProjectsRouteImport.update({
    id: '/settings/projects',
    path: '/settings/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsExportRoute =
  AuthenticatedSettingsExportRouteImport.update({
    id: '/settings/export',
    path: '/settings/export',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/reports/sales',
    path: '/reports/sales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRevenueRoute =
  AuthenticatedReportsRevenueRouteImport.update({
    id: '/reports/revenue',
    path: '/reports/revenue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsOccupancyRoute =
  AuthenticatedReportsOccupancyRouteImport.update({
    id: '/reports/occupancy',
    path: '/reports/occupancy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsCustomRoute =
  AuthenticatedReportsCustomRouteImport.update({
    id: '/reports/custom',
    path: '/reports/custom',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsCollectionRoute =
  AuthenticatedReportsCollectionRouteImport.update({
    id: '/reports/collection',
    path: '/reports/collection',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsDashboardRoute =
  AuthenticatedProjectsDashboardRouteImport.update({
    id: '/projects/dashboard',
    path: '/projects/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCustomerOverviewRoute =
  AuthenticatedProjectsCustomerOverviewRouteImport.update({
    id: '/projects/customer-overview',
    path: '/projects/customer-overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCreateRoute =
  AuthenticatedCustomersCreateRouteImport.update({
    id: '/customers/create',
    path: '/customers/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/customer-overview': typeof AuthenticatedProjectsCustomerOverviewRoute
  '/projects/dashboard': typeof AuthenticatedProjectsDashboardRoute
  '/reports/collection': typeof AuthenticatedReportsCollectionRoute
  '/reports/custom': typeof AuthenticatedReportsCustomRoute
  '/reports/occupancy': typeof AuthenticatedReportsOccupancyRoute
  '/reports/revenue': typeof AuthenticatedReportsRevenueRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/settings/export': typeof AuthenticatedSettingsExportRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/units/availability': typeof AuthenticatedUnitsAvailabilityRoute
  '/units/by-project': typeof AuthenticatedUnitsByProjectRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/units/': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/customer-overview': typeof AuthenticatedProjectsCustomerOverviewRoute
  '/projects/dashboard': typeof AuthenticatedProjectsDashboardRoute
  '/reports/collection': typeof AuthenticatedReportsCollectionRoute
  '/reports/custom': typeof AuthenticatedReportsCustomRoute
  '/reports/occupancy': typeof AuthenticatedReportsOccupancyRoute
  '/reports/revenue': typeof AuthenticatedReportsRevenueRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/settings/export': typeof AuthenticatedSettingsExportRoute
  '/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/units/availability': typeof AuthenticatedUnitsAvailabilityRoute
  '/units/by-project': typeof AuthenticatedUnitsByProjectRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/units': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/customer-overview': typeof AuthenticatedProjectsCustomerOverviewRoute
  '/_authenticated/projects/dashboard': typeof AuthenticatedProjectsDashboardRoute
  '/_authenticated/reports/collection': typeof AuthenticatedReportsCollectionRoute
  '/_authenticated/reports/custom': typeof AuthenticatedReportsCustomRoute
  '/_authenticated/reports/occupancy': typeof AuthenticatedReportsOccupancyRoute
  '/_authenticated/reports/revenue': typeof AuthenticatedReportsRevenueRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/settings/export': typeof AuthenticatedSettingsExportRoute
  '/_authenticated/settings/projects': typeof AuthenticatedSettingsProjectsRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/units/availability': typeof AuthenticatedUnitsAvailabilityRoute
  '/_authenticated/units/by-project': typeof AuthenticatedUnitsByProjectRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/units/': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/contacts'
    | '/customers/create'
    | '/projects/$projectId'
    | '/projects/customer-overview'
    | '/projects/dashboard'
    | '/reports/collection'
    | '/reports/custom'
    | '/reports/occupancy'
    | '/reports/revenue'
    | '/reports/sales'
    | '/settings/export'
    | '/settings/projects'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/users'
    | '/units/availability'
    | '/units/by-project'
    | '/customers/'
    | '/projects/'
    | '/reports/'
    | '/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/companies'
    | '/contacts'
    | '/'
    | '/customers/create'
    | '/projects/$projectId'
    | '/projects/customer-overview'
    | '/projects/dashboard'
    | '/reports/collection'
    | '/reports/custom'
    | '/reports/occupancy'
    | '/reports/revenue'
    | '/reports/sales'
    | '/settings/export'
    | '/settings/projects'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/users'
    | '/units/availability'
    | '/units/by-project'
    | '/customers'
    | '/projects'
    | '/reports'
    | '/units'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/'
    | '/_authenticated/customers/create'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/customer-overview'
    | '/_authenticated/projects/dashboard'
    | '/_authenticated/reports/collection'
    | '/_authenticated/reports/custom'
    | '/_authenticated/reports/occupancy'
    | '/_authenticated/reports/revenue'
    | '/_authenticated/reports/sales'
    | '/_authenticated/settings/export'
    | '/_authenticated/settings/projects'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/users'
    | '/_authenticated/units/availability'
    | '/_authenticated/units/by-project'
    | '/_authenticated/customers/'
    | '/_authenticated/projects/'
    | '/_authenticated/reports/'
    | '/_authenticated/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units/': {
      id: '/_authenticated/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof AuthenticatedUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units/by-project': {
      id: '/_authenticated/units/by-project'
      path: '/units/by-project'
      fullPath: '/units/by-project'
      preLoaderRoute: typeof AuthenticatedUnitsByProjectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units/availability': {
      id: '/_authenticated/units/availability'
      path: '/units/availability'
      fullPath: '/units/availability'
      preLoaderRoute: typeof AuthenticatedUnitsAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/projects': {
      id: '/_authenticated/settings/projects'
      path: '/settings/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AuthenticatedSettingsProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/export': {
      id: '/_authenticated/settings/export'
      path: '/settings/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof AuthenticatedSettingsExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/revenue': {
      id: '/_authenticated/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof AuthenticatedReportsRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/occupancy': {
      id: '/_authenticated/reports/occupancy'
      path: '/reports/occupancy'
      fullPath: '/reports/occupancy'
      preLoaderRoute: typeof AuthenticatedReportsOccupancyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/custom': {
      id: '/_authenticated/reports/custom'
      path: '/reports/custom'
      fullPath: '/reports/custom'
      preLoaderRoute: typeof AuthenticatedReportsCustomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/collection': {
      id: '/_authenticated/reports/collection'
      path: '/reports/collection'
      fullPath: '/reports/collection'
      preLoaderRoute: typeof AuthenticatedReportsCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/dashboard': {
      id: '/_authenticated/projects/dashboard'
      path: '/projects/dashboard'
      fullPath: '/projects/dashboard'
      preLoaderRoute: typeof AuthenticatedProjectsDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/customer-overview': {
      id: '/_authenticated/projects/customer-overview'
      path: '/projects/customer-overview'
      fullPath: '/projects/customer-overview'
      preLoaderRoute: typeof AuthenticatedProjectsCustomerOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/create': {
      id: '/_authenticated/customers/create'
      path: '/customers/create'
      fullPath: '/customers/create'
      preLoaderRoute: typeof AuthenticatedCustomersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersCreateRoute: typeof AuthenticatedCustomersCreateRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsCustomerOverviewRoute: typeof AuthenticatedProjectsCustomerOverviewRoute
  AuthenticatedProjectsDashboardRoute: typeof AuthenticatedProjectsDashboardRoute
  AuthenticatedReportsCollectionRoute: typeof AuthenticatedReportsCollectionRoute
  AuthenticatedReportsCustomRoute: typeof AuthenticatedReportsCustomRoute
  AuthenticatedReportsOccupancyRoute: typeof AuthenticatedReportsOccupancyRoute
  AuthenticatedReportsRevenueRoute: typeof AuthenticatedReportsRevenueRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedSettingsExportRoute: typeof AuthenticatedSettingsExportRoute
  AuthenticatedSettingsProjectsRoute: typeof AuthenticatedSettingsProjectsRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedUnitsAvailabilityRoute: typeof AuthenticatedUnitsAvailabilityRoute
  AuthenticatedUnitsByProjectRoute: typeof AuthenticatedUnitsByProjectRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedUnitsIndexRoute: typeof AuthenticatedUnitsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersCreateRoute: AuthenticatedCustomersCreateRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsCustomerOverviewRoute:
    AuthenticatedProjectsCustomerOverviewRoute,
  AuthenticatedProjectsDashboardRoute: AuthenticatedProjectsDashboardRoute,
  AuthenticatedReportsCollectionRoute: AuthenticatedReportsCollectionRoute,
  AuthenticatedReportsCustomRoute: AuthenticatedReportsCustomRoute,
  AuthenticatedReportsOccupancyRoute: AuthenticatedReportsOccupancyRoute,
  AuthenticatedReportsRevenueRoute: AuthenticatedReportsRevenueRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedSettingsExportRoute: AuthenticatedSettingsExportRoute,
  AuthenticatedSettingsProjectsRoute: AuthenticatedSettingsProjectsRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedUnitsAvailabilityRoute: AuthenticatedUnitsAvailabilityRoute,
  AuthenticatedUnitsByProjectRoute: AuthenticatedUnitsByProjectRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedUnitsIndexRoute: AuthenticatedUnitsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
