/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedUnitsIndexRouteImport } from './routes/_authenticated/units/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedUnitsByProjectRouteImport } from './routes/_authenticated/units/by-project'
import { Route as AuthenticatedUnitsAvailabilityRouteImport } from './routes/_authenticated/units/availability'
import { Route as AuthenticatedProjectsDashboardRouteImport } from './routes/_authenticated/projects/dashboard'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedCustomersCreateRouteImport } from './routes/_authenticated/customers/create'
import { Route as AuthenticatedContractsExpiringRouteImport } from './routes/_authenticated/contracts/expiring'
import { Route as AuthenticatedContractsCreateRouteImport } from './routes/_authenticated/contracts/create'
import { Route as AuthenticatedContractsContractIdIndexRouteImport } from './routes/_authenticated/contracts/$contractId/index'
import { Route as AuthenticatedContractsContractIdPrintRouteImport } from './routes/_authenticated/contracts/$contractId/print'
import { Route as AuthenticatedContractsContractIdEditRouteImport } from './routes/_authenticated/contracts/$contractId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnitsIndexRoute = AuthenticatedUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUnitsByProjectRoute =
  AuthenticatedUnitsByProjectRouteImport.update({
    id: '/units/by-project',
    path: '/units/by-project',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUnitsAvailabilityRoute =
  AuthenticatedUnitsAvailabilityRouteImport.update({
    id: '/units/availability',
    path: '/units/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsDashboardRoute =
  AuthenticatedProjectsDashboardRouteImport.update({
    id: '/projects/dashboard',
    path: '/projects/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCreateRoute =
  AuthenticatedCustomersCreateRouteImport.update({
    id: '/customers/create',
    path: '/customers/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsExpiringRoute =
  AuthenticatedContractsExpiringRouteImport.update({
    id: '/contracts/expiring',
    path: '/contracts/expiring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsCreateRoute =
  AuthenticatedContractsCreateRouteImport.update({
    id: '/contracts/create',
    path: '/contracts/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsContractIdIndexRoute =
  AuthenticatedContractsContractIdIndexRouteImport.update({
    id: '/contracts/$contractId/',
    path: '/contracts/$contractId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsContractIdPrintRoute =
  AuthenticatedContractsContractIdPrintRouteImport.update({
    id: '/contracts/$contractId/print',
    path: '/contracts/$contractId/print',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsContractIdEditRoute =
  AuthenticatedContractsContractIdEditRouteImport.update({
    id: '/contracts/$contractId/edit',
    path: '/contracts/$contractId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contracts/create': typeof AuthenticatedContractsCreateRoute
  '/contracts/expiring': typeof AuthenticatedContractsExpiringRoute
  '/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/dashboard': typeof AuthenticatedProjectsDashboardRoute
  '/units/availability': typeof AuthenticatedUnitsAvailabilityRoute
  '/units/by-project': typeof AuthenticatedUnitsByProjectRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/units/': typeof AuthenticatedUnitsIndexRoute
  '/contracts/$contractId/edit': typeof AuthenticatedContractsContractIdEditRoute
  '/contracts/$contractId/print': typeof AuthenticatedContractsContractIdPrintRoute
  '/contracts/$contractId/': typeof AuthenticatedContractsContractIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/': typeof AuthenticatedIndexRoute
  '/contracts/create': typeof AuthenticatedContractsCreateRoute
  '/contracts/expiring': typeof AuthenticatedContractsExpiringRoute
  '/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/dashboard': typeof AuthenticatedProjectsDashboardRoute
  '/units/availability': typeof AuthenticatedUnitsAvailabilityRoute
  '/units/by-project': typeof AuthenticatedUnitsByProjectRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/units': typeof AuthenticatedUnitsIndexRoute
  '/contracts/$contractId/edit': typeof AuthenticatedContractsContractIdEditRoute
  '/contracts/$contractId/print': typeof AuthenticatedContractsContractIdPrintRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/contracts/create': typeof AuthenticatedContractsCreateRoute
  '/_authenticated/contracts/expiring': typeof AuthenticatedContractsExpiringRoute
  '/_authenticated/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/dashboard': typeof AuthenticatedProjectsDashboardRoute
  '/_authenticated/units/availability': typeof AuthenticatedUnitsAvailabilityRoute
  '/_authenticated/units/by-project': typeof AuthenticatedUnitsByProjectRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/units/': typeof AuthenticatedUnitsIndexRoute
  '/_authenticated/contracts/$contractId/edit': typeof AuthenticatedContractsContractIdEditRoute
  '/_authenticated/contracts/$contractId/print': typeof AuthenticatedContractsContractIdPrintRoute
  '/_authenticated/contracts/$contractId/': typeof AuthenticatedContractsContractIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/contacts'
    | '/contracts/create'
    | '/contracts/expiring'
    | '/customers/create'
    | '/projects/$projectId'
    | '/projects/dashboard'
    | '/units/availability'
    | '/units/by-project'
    | '/contracts/'
    | '/customers/'
    | '/projects/'
    | '/units/'
    | '/contracts/$contractId/edit'
    | '/contracts/$contractId/print'
    | '/contracts/$contractId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/companies'
    | '/contacts'
    | '/'
    | '/contracts/create'
    | '/contracts/expiring'
    | '/customers/create'
    | '/projects/$projectId'
    | '/projects/dashboard'
    | '/units/availability'
    | '/units/by-project'
    | '/contracts'
    | '/customers'
    | '/projects'
    | '/units'
    | '/contracts/$contractId/edit'
    | '/contracts/$contractId/print'
    | '/contracts/$contractId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/'
    | '/_authenticated/contracts/create'
    | '/_authenticated/contracts/expiring'
    | '/_authenticated/customers/create'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/dashboard'
    | '/_authenticated/units/availability'
    | '/_authenticated/units/by-project'
    | '/_authenticated/contracts/'
    | '/_authenticated/customers/'
    | '/_authenticated/projects/'
    | '/_authenticated/units/'
    | '/_authenticated/contracts/$contractId/edit'
    | '/_authenticated/contracts/$contractId/print'
    | '/_authenticated/contracts/$contractId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units/': {
      id: '/_authenticated/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof AuthenticatedUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units/by-project': {
      id: '/_authenticated/units/by-project'
      path: '/units/by-project'
      fullPath: '/units/by-project'
      preLoaderRoute: typeof AuthenticatedUnitsByProjectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units/availability': {
      id: '/_authenticated/units/availability'
      path: '/units/availability'
      fullPath: '/units/availability'
      preLoaderRoute: typeof AuthenticatedUnitsAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/dashboard': {
      id: '/_authenticated/projects/dashboard'
      path: '/projects/dashboard'
      fullPath: '/projects/dashboard'
      preLoaderRoute: typeof AuthenticatedProjectsDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/create': {
      id: '/_authenticated/customers/create'
      path: '/customers/create'
      fullPath: '/customers/create'
      preLoaderRoute: typeof AuthenticatedCustomersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/expiring': {
      id: '/_authenticated/contracts/expiring'
      path: '/contracts/expiring'
      fullPath: '/contracts/expiring'
      preLoaderRoute: typeof AuthenticatedContractsExpiringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/create': {
      id: '/_authenticated/contracts/create'
      path: '/contracts/create'
      fullPath: '/contracts/create'
      preLoaderRoute: typeof AuthenticatedContractsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/$contractId/': {
      id: '/_authenticated/contracts/$contractId/'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId/'
      preLoaderRoute: typeof AuthenticatedContractsContractIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/$contractId/print': {
      id: '/_authenticated/contracts/$contractId/print'
      path: '/contracts/$contractId/print'
      fullPath: '/contracts/$contractId/print'
      preLoaderRoute: typeof AuthenticatedContractsContractIdPrintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/$contractId/edit': {
      id: '/_authenticated/contracts/$contractId/edit'
      path: '/contracts/$contractId/edit'
      fullPath: '/contracts/$contractId/edit'
      preLoaderRoute: typeof AuthenticatedContractsContractIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContractsCreateRoute: typeof AuthenticatedContractsCreateRoute
  AuthenticatedContractsExpiringRoute: typeof AuthenticatedContractsExpiringRoute
  AuthenticatedCustomersCreateRoute: typeof AuthenticatedCustomersCreateRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsDashboardRoute: typeof AuthenticatedProjectsDashboardRoute
  AuthenticatedUnitsAvailabilityRoute: typeof AuthenticatedUnitsAvailabilityRoute
  AuthenticatedUnitsByProjectRoute: typeof AuthenticatedUnitsByProjectRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedUnitsIndexRoute: typeof AuthenticatedUnitsIndexRoute
  AuthenticatedContractsContractIdEditRoute: typeof AuthenticatedContractsContractIdEditRoute
  AuthenticatedContractsContractIdPrintRoute: typeof AuthenticatedContractsContractIdPrintRoute
  AuthenticatedContractsContractIdIndexRoute: typeof AuthenticatedContractsContractIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContractsCreateRoute: AuthenticatedContractsCreateRoute,
  AuthenticatedContractsExpiringRoute: AuthenticatedContractsExpiringRoute,
  AuthenticatedCustomersCreateRoute: AuthenticatedCustomersCreateRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsDashboardRoute: AuthenticatedProjectsDashboardRoute,
  AuthenticatedUnitsAvailabilityRoute: AuthenticatedUnitsAvailabilityRoute,
  AuthenticatedUnitsByProjectRoute: AuthenticatedUnitsByProjectRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedUnitsIndexRoute: AuthenticatedUnitsIndexRoute,
  AuthenticatedContractsContractIdEditRoute:
    AuthenticatedContractsContractIdEditRoute,
  AuthenticatedContractsContractIdPrintRoute:
    AuthenticatedContractsContractIdPrintRoute,
  AuthenticatedContractsContractIdIndexRoute:
    AuthenticatedContractsContractIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
